CREATE TABLE FELIPE.COMUNA ( 
COD_COMUNA VARCHAR(2),
NAME_COMUNA VARCHAR(15),
KSM_2 DECIMAL,
CONSTRAINT PK_COD_COMUNA PRIMARY KEY(COD_COMUNA),
CONSTRAINT NN_NAME_COMUNA CHECK (NAME_COMUNA IS NOT NULL)
);


CREATE TABLE FELIPE.SUPPLIER(
NIT VARCHAR(20),
NAME_SUPPLIER VARCHAR(80),
ADRESS VARCHAR(40),
PHONE_NUMBER VARCHAR(15)
CONSTRAINT NN_NAME_SUPPLIER CHECK (NAME_SUPPLIER IS NOT NULL),
CONSTRAINT NN_PHONE_NUMBER CHECK (PHONE_NUMBER IS NOT NULL),
CONSTRAINT PK_NIT_SUPPLIER PRIMARY KEY (NIT)
);



CREATE TABLE FELIPE.BARRIO(
COD_COMUNA VARCHAR(2),
COD_BARRIO VARCHAR(2),
NAME_BARRIO VARCHAR(30),
CONSTRAINT NN_NAME_BARRIO CHECK (NAME_BARRIO IS NOT NULL),
CONSTRAINT FK_COD_COMUNA_BARRIO FOREIGN KEY (COD_COMUNA) REFERENCES FELIPE.COMUNA(COD_COMUNA),
CONSTRAINT PK_BARRIO PRIMARY KEY (COD_COMUNA ,COD_BARRIO) 
);


CREATE TABLE felipe.CLIENT (
DOCUMENT_CLIENT VARCHAR(15),
NAME1 VARCHAR(15),
NAME2 VARCHAR(15),
LAST_NAME1 VARCHAR(15),
LAST_NAME2 VARCHAR(15),
ADRESS VARCHAR(50),
SEX CHAR(1),
PHONE_NUMBER VARCHAR(20),
EMAIL VARCHAR(30),
COD_COMUNA VARCHAR(2),
COD_BARRIO VARCHAR(2),
CONSTRAINT CK_SEX_CLIENT CHECK (SEX IN ('M','F')),
CONSTRAINT NN_PHONE_NUMBER CHECK (PHONE_NUMBER IS NOT NULL),
CONSTRAINT FK_BARRIO_CLIENT FOREIGN KEY (COD_COMUNA,COD_BARRIO) REFERENCES FELIPE.BARRIO(COD_COMUNA, COD_BARRIO),
CONSTRAINT PK_CLIENT PRIMARY KEY(DOCUMENT_CLIENT)
);

CREATE TABLE FELIPE.PRODUCT(
COD_PRODUCT VARCHAR(4),
DESCRIPTION VARCHAR(100),
VALUE_PRODUCT INTEGER,
SIZE_PRODUCT VARCHAR(3),
COLOR VARCHAR(20),
NIT VARCHAR(20),
CONSTRAINT NN_DESCRIPTION CHECK (DESCRIPTION IS NOT NULL),
CONSTRAINT CK_VALUE_PRODUCT CHECK (VALUE_PRODUCT > 0),
CONSTRAINT CK_SIZE_PRODUCT CHECK (SIZE_PRODUCT IN ('S','M','L','XL','XXL')),
CONSTRAINT NN_COLOR CHECK (COLOR IS NOT NULL),
CONSTRAINT FK_PRODUCT_SUPPLIER FOREIGN KEY (NIT) REFERENCES FELIPE.SUPPLIER(NIT),
CONSTRAINT PK_COD_PRODUCT PRIMARY KEY (COD_PRODUCT)
);


CREATE TABLE FELIPE.FACTURA(
CONSECUTIVO SERIAL,
DATE_FACTURA DATE,
DOCUMENT_CLIENT VARCHAR(15),
DISCOUNT DECIMAL,
TOTAL DECIMAL,
CONSTRAINT NN_DATE_FACTURA CHECK (DATE_FACTURA IS NOT NULL),
CONSTRAINT FK_CLIENT_FACTURA FOREIGN KEY (DOCUMENT_CLIENT) REFERENCES FELIPE.CLIENT(DOCUMENT_CLIENT),
CONSTRAINT PK_FACTURA PRIMARY KEY (CONSECUTIVO)
);

CREATE TABLE FELIPE.DETAIL(
CONSECUTIVO INTEGER,
ORDINAL VARCHAR(2),
COD_PRODUCT VARCHAR(4),
QUANTITY INTEGER,
SUBTOTAL INTEGER,
DISCOUNT DECIMAL,
CONSTRAINT NN_ORDINAL CHECK (ORDINAL IS NOT NULL),
CONSTRAINT CK_QUANTITY CHECK (QUANTITY > 0),
CONSTRAINT FK_PRODUCT_DETAIL FOREIGN KEY (COD_PRODUCT) REFERENCES FELIPE.PRODUCT(COD_PRODUCT),
CONSTRAINT FK_FACTURA_DETAIL FOREIGN KEY (CONSECUTIVO) REFERENCES FELIPE.FACTURA(CONSECUTIVO),
CONSTRAINT PK_DETAIL PRIMARY KEY (CONSECUTIVO,ORDINAL)
);



